### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by geoffreyvd** [shalugin/horizontal-timeline#1]
I would like to use this library, if you have some time to provide a bit of documentation it would be very much appreciated, thank you in advance.

**Comment by shalugin** [comment]
@geoffreyvd I've added some documentation in README.md. See sample in horizontal-timeline-sample folder.

PR are welcome :)

**Comment by geoffreyvd** [comment]
@shalugin awesome! Apparantly the visibility property is false on default, I was wondering why it didn't show up :p
Thank you very much, have a good day!
